services:
  mysql:
    image: mysql:8.0.35
    container_name: ghost-mysql-full
    # We'll need to look into how we can further fine tune the memory usage/performance here
    command: --innodb-buffer-pool-size=1G --innodb-log-buffer-size=500M --innodb-change-buffer-max-size=50 --innodb-flush-log-at-trx_commit=0 --innodb-flush-method=O_DIRECT
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghost
    restart: always
    volumes:
      # Turns out you can drop .sql or .sql.gz files in here, cool!
      - ./mysql-preload:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql -uroot -proot ghost -e 'select 1'"
      interval: 1s
      retries: 120
  redis:
    image: redis:7.0
    container_name: ghost-redis-full
    ports:
      - "6379:6379"
    restart: always
  jaeger:
      image: jaegertracing/all-in-one:1.58
      container_name: ghost-jaeger-full
      ports:
        - "4318:4318"
        - "16686:16686"
        - "9411:9411"
      restart: always
      environment:
        COLLECTOR_ZIPKIN_HOST_PORT: :9411

  ghost:
    build:
      context: ../..
      dockerfile: .github/scripts/Dockerfile  # Specify the Dockerfile path
    container_name: ghost-full
    ports:
      - "2368:2368"
    environment:
      NODE_ENV: development
      DOCKER_FULL: true
      database__client: mysql
      database__connection__host: ghost-mysql
      database__connection__user: root
      database__connection__password: root
      database__connection__database: ghost
    volumes:
      - ../../:/opt/ghost
      - /opt/ghost/node_modules
    depends_on:
      - mysql
      - redis
      - jaeger
