# For use in a Dev Container where your local code is mounted into the container
name: ghost-devcontainer
services:
  ghost:
    build:
      context: ../../
      dockerfile: .devcontainer/.docker/Dockerfile
      target: base-devcontainer
      no_cache: true
    pull_policy: build
    command: ["sleep", "infinity"]
    environment:
      - DEVCONTAINER=true
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix