# Dev Container with all Ghost code and dependencies pre-installed
name: ghost-full-devcontainer
services:
  ghost:
    image: ghost-full-devcontainer
    build:
      target: full-devcontainer
    command: ["sleep", "infinity"]
    environment:
      - DEVCONTAINER=true
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix